/**
 * window.cowork.callMcpTool wrapper — the artifact's only I/O channel.
 *
 * Tool ids are FULL LITERALS in this bundle, carrying a placeholder the
 * `/edifice front` skill route substitutes with the live connector UUID.
 * They must not be assembled at runtime, and must not be read back from the
 * document's meta block: Cowork REGENERATES that block when it publishes the
 * artifact, deriving `mcpTools` from the ids it finds in the code. A bundle
 * that names no tool literally gets `mcpTools: []` — no resolvable id, and no
 * granted permission either, since that block is the permission manifest the
 * viewer approves. Observed 2026-07-28: an artifact published from a hydrated
 * file came back with `name: "Edifice Front"` and an empty tool list, while the
 * source file on disk still held the three correct ids.
 *
 * The reference artifact that does work (docs/reference-cowork-artifact-command-center.html)
 * declares its ids the same way — `const T_SPRINTS = "mcp__<uuid>__list_sprints"`.
 */

export type ErrorCode =
  | "no_cowork"
  | "not_hydrated"
  | "needs_reauth"
  | "server_not_connected"
  | "server_unavailable"
  | "upstream_error";

export class McpToolError extends Error {
  code: ErrorCode;
  constructor(code: ErrorCode, message: string) {
    super(message);
    this.name = "McpToolError";
    this.code = code;
  }
}

type ToolShortName = "list_edifice_missions" | "get_mission_context" | "get_mission_photo";

/**
 * Full connector tool ids. `PLACEHOLDER_HAL_MCP_UUID` is substituted by the
 * skill route with the value `ListConnectors` reports for hal-mcp — per-desktop,
 * never committed. Keep each id a single literal string: splitting or building
 * one by concatenation hides it from whatever Cowork scans at publish time.
 */
const TOOL_IDS: Record<ToolShortName, string> = {
  list_edifice_missions: "mcp__PLACEHOLDER_HAL_MCP_UUID__list_edifice_missions",
  get_mission_context: "mcp__PLACEHOLDER_HAL_MCP_UUID__get_mission_context",
  get_mission_photo: "mcp__PLACEHOLDER_HAL_MCP_UUID__get_mission_photo",
};

declare global {
  interface Window {
    cowork?: {
      callMcpTool: (name: string, args?: Record<string, unknown>) => Promise<McpToolResult>;
    };
  }
}

interface McpImageContent {
  type: "image";
  data: string;
  mimeType: string;
}

interface McpTextContent {
  type: "text";
  text: string;
}

type McpContent = McpImageContent | McpTextContent;

interface McpToolResult {
  isError?: boolean;
  content?: McpContent[];
  structuredContent?: unknown;
}

/**
 * Returns the tool's full id, refusing to call an un-hydrated build. Reaching
 * this error means the HTML was opened straight from the plugin instead of
 * being generated by `/edifice front`, which is the step that substitutes the
 * connector UUID.
 */
function resolveToolName(shortName: ToolShortName): string {
  const id = TOOL_IDS[shortName];
  if (id.includes("PLACEHOLDER")) {
    throw new McpToolError(
      "not_hydrated",
      `L'id de l'outil "${shortName}" contient encore son placeholder (${id}) : ` +
        `cet artefact n'a pas été généré par /edifice front.`,
    );
  }
  return id;
}

/**
 * Best-effort classification of a cowork.callMcpTool failure. The exact
 * error string shapes Cowork surfaces for each failure mode are not
 * documented publicly — this heuristic is unverified against a live
 * session and should be checked against real error text.
 * TODO: verify in Cowork — exact error message shapes per failure mode.
 */
function classifyError(raw: string): ErrorCode {
  const s = raw.toLowerCase();
  if (s.includes("reauth") || s.includes("authenticate") || s.includes("unauthorized")) {
    return "needs_reauth";
  }
  if (s.includes("not connected") || s.includes("no connector") || s.includes("not found")) {
    return "server_not_connected";
  }
  if (s.includes("timeout") || s.includes("unavailable") || s.includes("network")) {
    return "server_unavailable";
  }
  return "upstream_error";
}

function extractText(result: McpToolResult): string | null {
  const block = result.content?.find((c): c is McpTextContent => c.type === "text");
  return block ? block.text : null;
}

function extractImage(result: McpToolResult): McpImageContent | null {
  const block = result.content?.find((c): c is McpImageContent => c.type === "image");
  return block ?? null;
}

/** Calls a JSON-returning tool (list_edifice_missions, get_mission_context). */
export async function callJsonTool<T>(
  shortName: Extract<ToolShortName, "list_edifice_missions" | "get_mission_context">,
  args: Record<string, unknown> = {},
): Promise<T> {
  if (!window.cowork?.callMcpTool) {
    throw new McpToolError("no_cowork", "window.cowork indisponible — cet artefact ne fonctionne que dans Claude Cowork.");
  }
  const fullName = resolveToolName(shortName);
  let result: McpToolResult;
  try {
    result = await window.cowork.callMcpTool(fullName, args);
  } catch (err) {
    throw new McpToolError(classifyError(String(err)), String(err));
  }
  if (result.isError) {
    const text = extractText(result) ?? "Erreur outil MCP inconnue";
    throw new McpToolError(classifyError(text), text);
  }
  if (result.structuredContent != null) return result.structuredContent as T;
  const text = extractText(result);
  if (text != null) {
    try {
      return JSON.parse(text) as T;
    } catch {
      throw new McpToolError("upstream_error", `Réponse non-JSON de ${shortName}: ${text}`);
    }
  }
  throw new McpToolError("upstream_error", `Réponse vide de ${shortName}`);
}

/** Calls get_mission_photo and returns a data: URI (never a network URL). */
export async function callPhotoTool(
  photoId: string,
  maxWidth?: number,
): Promise<string> {
  if (!window.cowork?.callMcpTool) {
    throw new McpToolError("no_cowork", "window.cowork indisponible — cet artefact ne fonctionne que dans Claude Cowork.");
  }
  const fullName = resolveToolName("get_mission_photo");
  const args: Record<string, unknown> = { photo_id: photoId };
  if (maxWidth) args.max_width = maxWidth;
  let result: McpToolResult;
  try {
    result = await window.cowork.callMcpTool(fullName, args);
  } catch (err) {
    throw new McpToolError(classifyError(String(err)), String(err));
  }
  if (result.isError) {
    const text = extractText(result) ?? "Erreur outil MCP inconnue";
    throw new McpToolError(classifyError(text), text);
  }
  const image = extractImage(result);
  if (!image) {
    throw new McpToolError("upstream_error", `get_mission_photo n'a renvoyé aucune image pour ${photoId}`);
  }
  return `data:${image.mimeType};base64,${image.data}`;
}
